# Generated by Django 4.2 on 2024-02-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="role",
            field=models.TextField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=255,
                verbose_name="Пользовательская роль юзера",
            ),
        ),
    ]
