# Generated by Django 4.2 on 2024-02-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("question", "author"), name="unique_question_author"
            ),
        ),
    ]
