# Generated by Django 4.2 on 2024-02-06 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="parent_question",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="survey",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="text",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="title",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="author",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="survey",
        ),
        migrations.AddField(
            model_name="answer",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор выбранного ответа",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answer",
            name="choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="surveys.choice",
                verbose_name="Выбранный вариант ответа",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="parent_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.question",
            ),
        ),
    ]
