# Generated by Django 4.2 on 2024-02-07 08:18

import autoslug.fields
from django.db import migrations
import surveys.models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_answer_unique_question_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=155,
                populate_from=surveys.models.get_slug,
                unique=True,
                verbose_name="Слаг",
            ),
        ),
    ]
