# Generated by Django 4.2 on 2024-02-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_remove_survey_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="description",
            field=models.TextField(default=1, verbose_name="Тематика опроса"),
            preserve_default=False,
        ),
    ]
