# Generated by Django 4.2 on 2024-02-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_answer_parent_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Ответ"),
        ),
    ]
