# Generated by Django 4.2 on 2024-02-06 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_remove_answer_parent_question_remove_answer_survey_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="text",
        ),
    ]
