# Generated by Django 4.2 on 2024-02-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0004_alter_question_parent_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="parent_question",
        ),
        migrations.AddField(
            model_name="question",
            name="degree_question",
            field=models.TextField(
                blank=True,
                choices=[
                    ("parent", "Parent"),
                    ("child", "Child"),
                    ("last_child", "Last Child"),
                ],
                default="child",
                max_length=10,
                null=True,
            ),
        ),
    ]
