# Generated by Django 4.2 on 2024-02-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0005_remove_question_parent_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="degree_question",
            field=models.CharField(
                blank=True,
                choices=[
                    ("parent", "Parent"),
                    ("child", "Child"),
                    ("last_child", "Last Child"),
                ],
                default="child",
                max_length=10,
                null=True,
            ),
        ),
    ]
