# Generated by Django 4.2 on 2024-02-14 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0006_alter_question_degree_question"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="answer",
            name="unique_question_author",
        ),
    ]
