# Generated by Django 4.2 on 2024-02-17 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveys", "0008_alter_answer_author_alter_answer_choice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="answers_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор выбранного ответа",
            ),
        ),
    ]
